# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello/hello.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hello import resp_pb2 as hello_dot_resp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello/hello.proto',
  package='hello',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11hello/hello.proto\x12\x05hello\x1a\x10hello/resp.proto\"\xd1\x01\n\x0fGreetingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x03\x12,\n\x06m_type\x18\x03 \x01(\x0e\x32\x1c.hello.GreetingRequest.MType\x12\"\n\x07sub_msg\x18\x04 \x01(\x0b\x32\x11.hello.SubMessage\x12\x10\n\x06kernel\x18\x08 \x01(\tH\x00\x12\x10\n\x06signal\x18\t \x01(\rH\x00\"#\n\x05MType\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x42\x08\n\x06union1\"\'\n\nSubMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\x32\x44\n\x05Hello\x12;\n\x08greeting\x12\x16.hello.GreetingRequest\x1a\x17.hello.GreetingResponseb\x06proto3'
  ,
  dependencies=[hello_dot_resp__pb2.DESCRIPTOR,])



_GREETINGREQUEST_MTYPE = _descriptor.EnumDescriptor(
  name='MType',
  full_name='hello.GreetingRequest.MType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZERO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TWO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=211,
  serialized_end=246,
)
_sym_db.RegisterEnumDescriptor(_GREETINGREQUEST_MTYPE)


_GREETINGREQUEST = _descriptor.Descriptor(
  name='GreetingRequest',
  full_name='hello.GreetingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='hello.GreetingRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='hello.GreetingRequest.num', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_type', full_name='hello.GreetingRequest.m_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_msg', full_name='hello.GreetingRequest.sub_msg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kernel', full_name='hello.GreetingRequest.kernel', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signal', full_name='hello.GreetingRequest.signal', index=5,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GREETINGREQUEST_MTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='union1', full_name='hello.GreetingRequest.union1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=47,
  serialized_end=256,
)


_SUBMESSAGE = _descriptor.Descriptor(
  name='SubMessage',
  full_name='hello.SubMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='hello.SubMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='hello.SubMessage.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=297,
)

_GREETINGREQUEST.fields_by_name['m_type'].enum_type = _GREETINGREQUEST_MTYPE
_GREETINGREQUEST.fields_by_name['sub_msg'].message_type = _SUBMESSAGE
_GREETINGREQUEST_MTYPE.containing_type = _GREETINGREQUEST
_GREETINGREQUEST.oneofs_by_name['union1'].fields.append(
  _GREETINGREQUEST.fields_by_name['kernel'])
_GREETINGREQUEST.fields_by_name['kernel'].containing_oneof = _GREETINGREQUEST.oneofs_by_name['union1']
_GREETINGREQUEST.oneofs_by_name['union1'].fields.append(
  _GREETINGREQUEST.fields_by_name['signal'])
_GREETINGREQUEST.fields_by_name['signal'].containing_oneof = _GREETINGREQUEST.oneofs_by_name['union1']
DESCRIPTOR.message_types_by_name['GreetingRequest'] = _GREETINGREQUEST
DESCRIPTOR.message_types_by_name['SubMessage'] = _SUBMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGREQUEST,
  '__module__' : 'hello.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.GreetingRequest)
  })
_sym_db.RegisterMessage(GreetingRequest)

SubMessage = _reflection.GeneratedProtocolMessageType('SubMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBMESSAGE,
  '__module__' : 'hello.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.SubMessage)
  })
_sym_db.RegisterMessage(SubMessage)



_HELLO = _descriptor.ServiceDescriptor(
  name='Hello',
  full_name='hello.Hello',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=299,
  serialized_end=367,
  methods=[
  _descriptor.MethodDescriptor(
    name='greeting',
    full_name='hello.Hello.greeting',
    index=0,
    containing_service=None,
    input_type=_GREETINGREQUEST,
    output_type=hello_dot_resp__pb2._GREETINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLO)

DESCRIPTOR.services_by_name['Hello'] = _HELLO

# @@protoc_insertion_point(module_scope)
